
meta:
  name: "minio-ingestion-benchmark"
  description: "Benchmark for measuring MinIO ingestion throughput using S3 uploads"
  author: "LucaLM02"
  created_at: "2025-10-16T10:00:00Z"
  commit: "b4e5c6d7"
  image_hash: "docker://minio/minio@sha256:abcdef1234567890"

global:
  workspace: "/scratch/bench/minio-ingest"
  timeout: 7200
  environment:
    - BENCH_MODE=production

services:
  - id: "minio-01"
    role: "object-storage"
    executor:
      type: "apptainer"
      image: "/images/minio_latest.sif"
      cmd: ["minio", "server", "/data"]
      slurm:
        nodes: 1
        cpus: 8
        gpus: 0
        mem: "32G"
    healthcheck:
      cmd: ["curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5
      timeout: 10
      retries: 6
    monitor: "prometheus-node"
    logger: "file-compact"
    network:
      ports: [9000]

clients:
  - id: "s3-uploader-1"
    type: "s3-upload"
    executor:
      type: "slurm"
      slurm:
        nodes: [1]
        tasks_per_node: [2]
        cpus: [4]
        gpus: [0]
        mem: "16G"
    workload:
      target: "minio-01:9000"
      mode: "upload"
    monitor: "prometheus-node"
    logger: "file-compact"
    retries:
      attempts: 3
      backoff: 5

monitors:
  - id: "prometheus-node"
    type: "prometheus"
    config:
      scrape_targets: ["minio-01:9100", "s3-uploader-1:9100"]
      scrape_interval: 5
    collect_interval: 10
    save_as: "prom_snapshot.json"

loggers:
  - id: "file-compact"
    type: "file"
    paths: ["${global.workspace}/logs/*.log"]
    format: "json"

execution:
  warmup: 60
  duration: 600
  replicas: 1
  post_actions: ["collect_metrics", "collect_logs", "stop_services"]

reporting:
  outputs:
    - type: "csv"
      file: "metrics_summary.csv"
    - type: "pdf"
      file: "final_report.pdf"

notifications:
  webhook: "https://hooks.example.org/notify"

cleanup:
  remove_containers: true
  preserve_artifacts: false
